server:
  port: 9998
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb://root:admin123@18.215.234.170:27017/?authSource=admin
      database: production_order
  mvc:
    pathmatch:
      matching-strategy: "path-pattern-parser"
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: us-east-1
    sqs:
      enabled: true
      endpoint: ${AWS_ENDPOINT_URL}
  #security:
  #  oauth2:
  #    client:
  #      provider:
  #        cognito:
  #          issuer-uri: ${AWS_COGNITO_ISSUER_URI} #TODO - retirar
  #      registration:
  ##        cognito:
  #          client-id: ${AWS_COGNITO_CLIENT_ID} #TODO - retirar
  #          client-secret: ${AWS_COGNITO_CLIENT_SECRET} #TODO - retirar
  #          scope: openid

#application:
#  security:
#    jwt:
#      secret-key: ${JWT_SECRET_KEY}
#      expiration: 864000000 # 10 day
#      refresh-token:
#        expiration: 6048000000 # 70 days

#cognito:
#  user-pool-id: ${AWS_COGNITO_USER_POOL_ID} #TODO - retirar

app:
  queue-sqs:
    name: ${AWS_SQS_QUEUE_NAME}
  queue-status-sqs:
    name: ${AWS_SQS_QUEUE_STATUS_NAME}
